---
name: Eli
surname: Felts
position: "Fisheries Biologist"
address: "20046 Ryegrass Lane, Lenore, Idaho 83541"
phone: 605-695-1714
email: "elifelts@gmail.com"
date: "`r format(Sys.time(), '%B %Y')`"
headcolor: 414141
output:
  vitae::awesomecv:
    page_total: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE, warning = FALSE, message = FALSE)
library(vitae)
library(tidyverse)
library(googlesheets4)
```

```{r starter_keys}


```


```{r read_google}

cv_url <- "https://docs.google.com/spreadsheets/d/1DfPyPFa4xboyjm8dAbTzFnFTgo2oSbx0Auj1pa6RwAo/edit?gid=0#gid=0"

```


# Education

```{r echo=FALSE}

state_key <- tibble(institution_state=state.name,
                     state=state.abb)


education.df <- read_sheet(cv_url,sheet="education")%>% 
  left_join(state_key,by="institution_state") %>% 
  mutate(display_degree=str_c(degree,major,sep=", "),
         display_year=year(completion_date),
         display_institution=institution,
         display_where=str_c(institution_city,state,sep=", "))



```


```{r}

detailed_entries(education.df,
                 what=display_degree,
                 when=display_year,
                 with=display_institution,
                 where=display_where)

```

# Nobel Prizes

```{r}
tribble(
  ~Year, ~Type, ~Desc,
  1903, "Physics", "Awarded for her work on radioactivity with Pierre Curie and Henri Becquerel",
  1911, "Chemistry", "Awarded for the discovery of radium and polonium"
) %>%
  brief_entries(
    glue::glue("Nobel Prize in {Type}"),
    Year,
    Desc
  )
```

# Publications

```{r}
library(dplyr)
knitr::write_bib(c("vitae", "tibble"), "packages.bib")

bibliography_entries("packages.bib") %>%
  arrange(desc(author$family), issued)
```
